import axios from 'axios';
import * as cheerio from 'cheerio';
import OpenAI from 'openai';
import * as dotenv from 'dotenv';
import * as fs from 'fs';

dotenv.config();

const openai = process.env.OPENAI_API_KEY ? new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
}) : null;

async function generateReport(): Promise<string> {
  const date = new Date().toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    weekday: 'long'
  });

  // 收集数据
  const [news, weather, schedule] = await Promise.all([
    fetchAINews(),
    fetchWeather(),
    fetchSchedule()
  ]);

  // 生成 AI 总结
  const summary = await generateAISummary(news, weather, schedule);

  // 组装报告
  const report = `# 📰 ${date} 晨报

## 🤖 AI 速递
${news.map(n => `- ${n}`).join('\n')}

## 🌤️ 今日天气
- **温度**: ${weather.temp}
- **天气**: ${weather.condition}
- **建议**: ${weather.suggestion}

## 📅 今日待办
${schedule.map(s => `- [ ] ${s}`).join('\n')}

## 💡 AI 每日洞察
${summary}

---
🤖 Generated by AI Daily Reporter | [GitHub](https://github.com/Yuan9527-ai/ai-daily-reporter)
`;

  return report;
}

async function fetchAINews(): Promise<string[]> {
  // 实际项目中这里会爬取真实的 AI 新闻源
  return [
    '🚀 OpenAI 发布 GPT-5 预览版 - 性能提升 10x',
    '🤖 Anthropic Claude 4 发布 - 上下文窗口达到 1M tokens',
    '🧠 Google Gemini 2.0 突破 - 多模态理解能力大幅提升',
    '💡 Mistral AI 获得 6 亿欧元融资',
    '🔮 AI Agent 成为 2026 年最热门赛道'
  ];
}

async function fetchWeather(): Promise<{ temp: string; condition: string; suggestion: string }> {
  // 实际项目中会调用天气 API
  const hour = new Date().getHours();
  const suggestion = hour < 12 ? '上午适合专注工作' : 
                     hour < 18 ? '下午记得补充能量' : '晚上注意休息';
  
  return {
    temp: '15-25°C',
    condition: '晴朗 ☀️',
    suggestion
  };
}

async function fetchSchedule(): Promise<string[]> {
  // 实际项目中会连接 Google Calendar / Outlook
  const today = new Date().getDay();
  if (today === 0 || today === 6) {
    return ['🎉 周末休息', '📚 学习新技能', '🏃 户外运动'];
  }
  
  return [
    '10:00 - 产品需求评审会议',
    '14:00 - 技术方案讨论',
    '16:00 - 1:1 with Leo',
    '18:00 - 团队复盘'
  ];
}

async function generateAISummary(
  news: string[],
  weather: { condition: string; suggestion: string },
  schedule: string[]
): Promise<string> {
  if (!openai) {
    return '**今日重点**: AI 领域持续高速发展，天气宜人，适合专注工作。记得查看最新 AI 动态！';
  }

  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        {
          role: 'system',
          content: '你是一个助手，负责根据每日信息生成简洁有洞察的总结（100字以内）'
        },
        {
          role: 'user',
          content: `请总结今天的晨报信息：
新闻: ${news.join(', ')}
天气: ${weather.condition}
日程: ${schedule.length} 个待办事项

要求：简洁、有洞察、鼓舞人心`
        }
      ],
      max_tokens: 200
    });

    return response.choices[0].message.content || '今日充满机遇，保持专注！';
  } catch (error) {
    console.error('AI summary failed:', error);
    return '**今日重点**: AI 领域持续高速发展，天气宜人，适合专注工作。';
  }
}

// 主函数
async function main() {
  console.log('🤖 开始生成今日晨报...\n');
  
  const report = await generateReport();
  
  // 保存到文件
  const filename = `daily-report-${new Date().toISOString().split('T')[0]}.md`;
  fs.writeFileSync(filename, report);
  
  console.log(report);
  console.log(`\n✅ 报告已保存到: ${filename}`);
}

main().catch(console.error);
